"""empty message

Revision ID: 115a5502ebad
Revises: f6567959215b
Create Date: 2022-12-21 23:16:06.939434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115a5502ebad'
down_revision = 'f6567959215b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
