"""empty message

Revision ID: 232faff2bb53
Revises: 
Create Date: 2023-01-09 19:03:53.731592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232faff2bb53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=950), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('tour_duration', sa.String(length=120), nullable=True),
    sa.Column('destinations', sa.String(length=120), nullable=True),
    sa.Column('activities', sa.String(length=120), nullable=True),
    sa.Column('transport', sa.String(length=120), nullable=True),
    sa.Column('lodging', sa.String(length=120), nullable=True),
    sa.Column('overview_title', sa.String(length=120), nullable=True),
    sa.Column('overview_acomodation', sa.String(length=120), nullable=True),
    sa.Column('overview_description', sa.String(length=999), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=999), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('packages')
    # ### end Alembic commands ###
