"""empty message

Revision ID: 37e49e7f0b9d
Revises: ee663fef5330
Create Date: 2022-12-19 09:36:56.668501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e49e7f0b9d'
down_revision = 'ee663fef5330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('tour_duration', sa.String(length=120), nullable=True),
    sa.Column('destinations', sa.String(length=120), nullable=True),
    sa.Column('activities', sa.String(length=120), nullable=True),
    sa.Column('transport', sa.String(length=120), nullable=True),
    sa.Column('lodging', sa.String(length=120), nullable=True),
    sa.Column('overview_title', sa.String(length=120), nullable=True),
    sa.Column('overview_acomodation', sa.String(length=120), nullable=True),
    sa.Column('overview_description', sa.String(length=999), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activities'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('destinations'),
    sa.UniqueConstraint('lodging'),
    sa.UniqueConstraint('overview_acomodation'),
    sa.UniqueConstraint('overview_description'),
    sa.UniqueConstraint('overview_title'),
    sa.UniqueConstraint('package_name'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('tour_duration'),
    sa.UniqueConstraint('transport')
    )
    op.create_table('favPackages',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('packages_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['packages_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'packages_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['country'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('country')
        batch_op.drop_column('username')

    op.drop_table('favPackages')
    op.drop_table('packages')
    # ### end Alembic commands ###
