"""empty message

Revision ID: 9c40e67d0204
Revises: fcffd250d566
Create Date: 2023-01-06 18:37:16.864359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c40e67d0204'
down_revision = 'fcffd250d566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.String(length=999), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
