"""empty message

Revision ID: 9e697bcbd296
Revises: 248abfe93fef
Create Date: 2023-01-07 13:24:09.744478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e697bcbd296'
down_revision = '248abfe93fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview_title1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description1', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description2', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title3', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation3', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description3', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title4', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation4', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description4', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title5', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation5', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description5', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title6', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation6', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description6', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title7', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation7', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description7', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title8', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation8', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description8', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title9', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation9', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description9', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title10', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation10', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description10', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title11', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation11', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description11', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title12', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation12', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description12', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title13', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation13', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description13', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title14', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation14', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description14', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('overview_title15', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_acomodation15', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('overview_description15', sa.String(length=999), nullable=True))
        batch_op.add_column(sa.Column('url1', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url2', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url3', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url4', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url5', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url6', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url7', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url8', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url9', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url10', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url11', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url12', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url13', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url14', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('url15', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('url15')
        batch_op.drop_column('url14')
        batch_op.drop_column('url13')
        batch_op.drop_column('url12')
        batch_op.drop_column('url11')
        batch_op.drop_column('url10')
        batch_op.drop_column('url9')
        batch_op.drop_column('url8')
        batch_op.drop_column('url7')
        batch_op.drop_column('url6')
        batch_op.drop_column('url5')
        batch_op.drop_column('url4')
        batch_op.drop_column('url3')
        batch_op.drop_column('url2')
        batch_op.drop_column('url1')
        batch_op.drop_column('overview_description15')
        batch_op.drop_column('overview_acomodation15')
        batch_op.drop_column('overview_title15')
        batch_op.drop_column('overview_description14')
        batch_op.drop_column('overview_acomodation14')
        batch_op.drop_column('overview_title14')
        batch_op.drop_column('overview_description13')
        batch_op.drop_column('overview_acomodation13')
        batch_op.drop_column('overview_title13')
        batch_op.drop_column('overview_description12')
        batch_op.drop_column('overview_acomodation12')
        batch_op.drop_column('overview_title12')
        batch_op.drop_column('overview_description11')
        batch_op.drop_column('overview_acomodation11')
        batch_op.drop_column('overview_title11')
        batch_op.drop_column('overview_description10')
        batch_op.drop_column('overview_acomodation10')
        batch_op.drop_column('overview_title10')
        batch_op.drop_column('overview_description9')
        batch_op.drop_column('overview_acomodation9')
        batch_op.drop_column('overview_title9')
        batch_op.drop_column('overview_description8')
        batch_op.drop_column('overview_acomodation8')
        batch_op.drop_column('overview_title8')
        batch_op.drop_column('overview_description7')
        batch_op.drop_column('overview_acomodation7')
        batch_op.drop_column('overview_title7')
        batch_op.drop_column('overview_description6')
        batch_op.drop_column('overview_acomodation6')
        batch_op.drop_column('overview_title6')
        batch_op.drop_column('overview_description5')
        batch_op.drop_column('overview_acomodation5')
        batch_op.drop_column('overview_title5')
        batch_op.drop_column('overview_description4')
        batch_op.drop_column('overview_acomodation4')
        batch_op.drop_column('overview_title4')
        batch_op.drop_column('overview_description3')
        batch_op.drop_column('overview_acomodation3')
        batch_op.drop_column('overview_title3')
        batch_op.drop_column('overview_description2')
        batch_op.drop_column('overview_acomodation2')
        batch_op.drop_column('overview_title2')
        batch_op.drop_column('overview_description1')
        batch_op.drop_column('overview_acomodation1')
        batch_op.drop_column('overview_title1')

    # ### end Alembic commands ###
