"""empty message

Revision ID: b6f68b6b3f4e
Revises: 37e49e7f0b9d
Create Date: 2022-12-19 11:38:54.249196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f68b6b3f4e'
down_revision = '37e49e7f0b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint('packages_activities_key', type_='unique')
        batch_op.drop_constraint('packages_description_key', type_='unique')
        batch_op.drop_constraint('packages_destinations_key', type_='unique')
        batch_op.drop_constraint('packages_lodging_key', type_='unique')
        batch_op.drop_constraint('packages_overview_acomodation_key', type_='unique')
        batch_op.drop_constraint('packages_overview_description_key', type_='unique')
        batch_op.drop_constraint('packages_overview_title_key', type_='unique')
        batch_op.drop_constraint('packages_package_name_key', type_='unique')
        batch_op.drop_constraint('packages_title_key', type_='unique')
        batch_op.drop_constraint('packages_tour_duration_key', type_='unique')
        batch_op.drop_constraint('packages_transport_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_country_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_country_key', ['country'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_unique_constraint('packages_transport_key', ['transport'])
        batch_op.create_unique_constraint('packages_tour_duration_key', ['tour_duration'])
        batch_op.create_unique_constraint('packages_title_key', ['title'])
        batch_op.create_unique_constraint('packages_package_name_key', ['package_name'])
        batch_op.create_unique_constraint('packages_overview_title_key', ['overview_title'])
        batch_op.create_unique_constraint('packages_overview_description_key', ['overview_description'])
        batch_op.create_unique_constraint('packages_overview_acomodation_key', ['overview_acomodation'])
        batch_op.create_unique_constraint('packages_lodging_key', ['lodging'])
        batch_op.create_unique_constraint('packages_destinations_key', ['destinations'])
        batch_op.create_unique_constraint('packages_description_key', ['description'])
        batch_op.create_unique_constraint('packages_activities_key', ['activities'])

    # ### end Alembic commands ###
