"""empty message

Revision ID: f6567959215b
Revises: c628a8050581
Create Date: 2022-12-20 14:55:49.244093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6567959215b'
down_revision = 'c628a8050581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_packages', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_packages'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_shopping', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_shopping'], ['shopping.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favPackages')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('premium_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')
        batch_op.drop_column('premium_user')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.create_table('favPackages',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('packages_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['packages_id'], ['packages.id'], name='favPackages_packages_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], name='favPackages_users_id_fkey'),
    sa.PrimaryKeyConstraint('users_id', 'packages_id', name='favPackages_pkey')
    )
    op.drop_table('order_history')
    op.drop_table('shopping')
    op.drop_table('review')
    op.drop_table('favorites')
    # ### end Alembic commands ###
